# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: http.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='http.proto',
  package='http',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nhttp.proto\x12\x04http\"\x14\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x18\n\x07\x46riends\x12\r\n\x05names\x18\x01 \x03(\t20\n\x03\x44uo\x12)\n\nGetFriends\x12\n.http.User\x1a\r.http.Friends\"\x00\x62\x06proto3'
)




_USER = _descriptor.Descriptor(
  name='User',
  full_name='http.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='http.User.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=40,
)


_FRIENDS = _descriptor.Descriptor(
  name='Friends',
  full_name='http.Friends',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='names', full_name='http.Friends.names', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=66,
)

DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['Friends'] = _FRIENDS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'http_pb2'
  # @@protoc_insertion_point(class_scope:http.User)
  })
_sym_db.RegisterMessage(User)

Friends = _reflection.GeneratedProtocolMessageType('Friends', (_message.Message,), {
  'DESCRIPTOR' : _FRIENDS,
  '__module__' : 'http_pb2'
  # @@protoc_insertion_point(class_scope:http.Friends)
  })
_sym_db.RegisterMessage(Friends)



_DUO = _descriptor.ServiceDescriptor(
  name='Duo',
  full_name='http.Duo',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=68,
  serialized_end=116,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetFriends',
    full_name='http.Duo.GetFriends',
    index=0,
    containing_service=None,
    input_type=_USER,
    output_type=_FRIENDS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DUO)

DESCRIPTOR.services_by_name['Duo'] = _DUO

# @@protoc_insertion_point(module_scope)
